import { Fragment } from "react";
import "../styles/globals.css";
import Head from "next/head";
import Script from "next/script";
import Header from "../components/Header";
import Footer from "../components/Footer";

function MyApp({ Component, pageProps }) {
  return (
    <Fragment>
      <Script src="https://cdn.jsdelivr.net/npm/flowbite@2.3.0/js/flowbite.min.js"></Script>
      <Head>
        <title>MyEcommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-col relative">
        <Header />
        <Component {...pageProps} />
        <Footer />
      </main>
    </Fragment>
  );
}

export default MyApp;
